### Product endpoints

### Get all products
GET http://127.0.0.1:8000/products/products

### Get product by id
GET http://127.0.0.1:8000/products/product/{id}

### Create product
POST http://127.0.0.1:8000/products/product
```json
{
    "name": "Product 1",
    "description": "Description 1",
    "price": 100
}
```

### Update product
PUT http://127.0.0.1:8000/products/{id}
```json
{
    "name": "Product 1",
    "description": "Description 1",
    "price": 100
}
```

### Delete product
DELETE http://127.0.0.1:8000/products/{id}
